### ISSUE TITLE
How can I make each sub-option a navigable link?

### ISSUE THREAD

**Issue by gustavlu** [BilalBouk/reactstrap-basic-sidebar#1]
I'm new to react and I would like to know how can I make each option linkable to another page.

**Comment by BilalBouk** [comment]
if you are using react-router you can just change `<NavLink href="#">....</NavLink>` to `<NavLink tag={Link} to="/some-page">...</NavLink>` where  'Link' is imported from 'react-router-dom'

**Comment by gustavlu** [comment]
thanks
