### ISSUE TITLE
How to make the left-menu panel fixed/sticky?

### ISSUE THREAD

**Issue by andrwo** [BilalBouk/reactstrap-basic-sidebar#2]
I am trying to figure out how to make the left menu panel sticky (i.e. independently scroll from the main content page on the right), but can't get it right. Any ideas?

**Comment by BilalBouk** [comment]
sorry for the delay, if you're still interested i think one way to achieve that would be wrapping the left menu panel by a div and give it a static height and overflow: scroll for example :
`<div style={{height: 'calc(100vh - 130px)',overflowY: 'scroll'}}><Nav vertical className="list-unstyled pb-3">.....</Nav></div>`
